#!/bin/bash

if [ "$1" = "show" ]; then
  cat Documentation.md
  exit 0
fi

mkdir -p build/

cmake -S . -B build/
cmake --build build/

if [ "$1" = "run" ]; then
  echo "Запуск основной программы..."
  ./build/bin/my_program
elif [ "$1" = "test1" ]; then
  echo "Запуск простого теста..."
  ./build/bin/test1
elif [ "$1" = "test2" ]; then
  echo "Запуск сложного теста..."
  ./build/bin/test2
elif [ "$1" = "clean" ]; then
  echo "Чистка!!!"
  rm -rf ./build/*
fi